var graph = { "nodes":[{"name":"Новости УР", "track":0, "value":220, "rating":95, "speakers":""},
{"name":"Экстерн IE10+ 2018", "track":1, "value":53, "rating":46, "speakers":"Евгений Дегтярев"},
{"name":"Трудности перехода", "track":1, "value":32, "rating":34, "speakers":"Денис Омельков"},
{"name":"Пиксель Шрёдингера", "track":1, "value":41, "rating":70, "speakers":"Дмитрий Титаренко, Михаил Шатихин"},
{"name":"Backend VS Frontend", "track":1, "value":57, "rating":64, "speakers":"Евгений Тихонов"},
{"name":"Мама, я похакала!", "track":1, "value":68, "rating":97, "speakers":"Дмитрий Титаренко, Дмитрий Симонов"},
{"name":"Jump-start\nпо нагрузочному\nтестированию", "track":1, "value":51, "rating":80, "speakers":"Сергей Рожин"},
{"name":"Контур\nи Data Science", "track":1, "value":60, "rating":45, "speakers":"Павел Киселёв, Никита Тарасов"},
{"name":"Делаем как можем", "track":2, "value":78, "rating":68, "speakers":"Сергей Соловьев"},
{"name":"Почему Экстерну\nне страшно", "track":2, "value":101, "rating":90, "speakers":"Евгений Шишкин"},
{"name":"Техподдержка,\nкоторую заслужили", "track":2, "value":90, "rating":87, "speakers":"Ксения Скачкова"},
{"name":"Где ЭЦП получали,\nтуда и идите", "track":2, "value":69, "rating":47, "speakers":"Антон Телегин"},
{"name":"Тряхнём бэклогом,\nстарина", "track":2, "value":66, "rating":76, "speakers":"Лев Плинер"},
{"name":"Не терять Фокус", "track":2, "value":53, "rating":46, "speakers":"Валерия Ромащенко"},
{"name":"Качество необходимое\nи достаточное", "track":2, "value":58, "rating":46, "speakers":"Максим Нахабо"},
{"name":"Качество,\nза которое платят", "track":2, "value":57, "rating":70, "speakers":"Алексей Жуков"},
{"name":"Откуда берутся\nдолгосрочные планы", "track":0, "value":178, "rating":80, "speakers":"Леонид Волков"},
{"name":"Почему уходят разработчики", "track":0, "value":150, "rating":85, "speakers":"Игорь Устюжанин"},
{"name":"Ты тоже менеджер!", "track":0, "value":140, "rating":89, "speakers":"Павел Егоров"},
{"name":"Фигали ты ноешь?", "track":0, "value":120, "rating":66, "speakers":"Ксения Окунцева, Иван Ильин"},
{"name":"Набор на стажировку.\nАнализируй это", "track":0, "value":92, "rating":65, "speakers":"Юлия Закс"},
{"name":"Пять пороков команды", "track":0, "value":74, "rating":43, "speakers":"Виктор Кандоба"},
{"name":"Лебедь, рак и щука", "track":0, "value":69, "rating":51, "speakers":"Андрей Соколов"},
{"name":"Мастерклассы 1", "track":3, "value":65, "rating":89, "speakers":""},
{"name":"Мастерклассы 2", "track":3, "value":55, "rating":82, "speakers":""},
{"name":"ЧГК", "track":0, "value":112, "rating":100, "speakers":""}],
"links":[{"source":0, "target":1, "value":53 },
{"source":0, "target":8, "value":78 },
{"source":0, "target":23, "value":63 },
{"source":1, "target":2, "value":30 },
{"source":1, "target":9, "value":20 },
{"source":2, "target":3, "value":28 },
{"source":2, "target":10, "value":4 },
{"source":3, "target":4, "value":35 },
{"source":3, "target":11, "value":3 },
{"source":4, "target":5, "value":35 },
{"source":4, "target":12, "value":8 },
{"source":4, "target":24, "value":9 },
{"source":5, "target":6, "value":44 },
{"source":5, "target":13, "value":4 },
{"source":6, "target":7, "value":44 },
{"source":7, "target":16, "value":46 },
{"source":8, "target":2, "value":1 },
{"source":8, "target":9, "value":72 },
{"source":9, "target":3, "value":11 },
{"source":9, "target":10, "value":81 },
{"source":10, "target":4, "value":15 },
{"source":10, "target":11, "value":62 },
{"source":11, "target":5, "value":8 },
{"source":11, "target":12, "value":37 },
{"source":11, "target":24, "value":17 },
{"source":12, "target":6, "value":3 },
{"source":12, "target":13, "value":47 },
{"source":13, "target":7, "value":2 },
{"source":13, "target":14, "value":46 },
{"source":14, "target":7, "value":1 },
{"source":14, "target":15, "value":49 },
{"source":15, "target":16, "value":51 },
{"source":16, "target":25, "value":93 },
{"source":17, "target":18, "value":138 },
{"source":18, "target":19, "value":113 },
{"source":19, "target":20, "value":83 },
{"source":20, "target":21, "value":70 },
{"source":21, "target":22, "value":67 },
{"source":23, "target":5, "value":18 },
{"source":23, "target":12, "value":14 },
{"source":23, "target":24, "value":23 },
{"source":24, "target":16, "value":41 },
{"source":25, "target":17, "value":88 }]}